# Kết nối Database
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:cinema1}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cấu hình đường dẫn Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha

# Định dạng ngày tháng
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+7

# Cấu hình GMAIL SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Thay bằng email của Kiên
spring.mail.username=kienphatanh@gmail.com 
# Dán mã 16 ký tự vừa tạo vào đây
spring.mail.password=teueetpougwmdjwe

# Các thông số kỹ thuật bắt buộc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Cấu hình Cloudinary
cloudinary.cloud_name=dekxmzenc
cloudinary.api_key=461383548288247
cloudinary.api_secret=VTNmOeo7tgcgqdKVPivetBD9sJ0

# ==========================================
# CẤU HÌNH VNPAY (DÙNG CHO THANH TOÁN)
# ==========================================
# VNPAY CONFIGURATION
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.tmnCode=F49D0UJB
vnpay.hashSecret=JVHVV89GE5N3FHVDXW39682DL1V889JX
# Duy để 8080 để test xem nó có nhảy status trong DB không trước nhé
vnpay.returnUrl=http://localhost:8080/api/v1/orders/vnpay-callback